// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbgyPXzgGbkcagU92s29iwIAVS6iCIQpY',
    appId: '1:849158029445:web:55f53a1b7872374a9de9ec',
    messagingSenderId: '849158029445',
    projectId: 'cookiefactory-8018b',
    authDomain: 'cookiefactory-8018b.firebaseapp.com',
    storageBucket: 'cookiefactory-8018b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKSk66QE33tlNw6NMxIkvGuVVaC8TR3D0',
    appId: '1:849158029445:android:4177d9b106aecee09de9ec',
    messagingSenderId: '849158029445',
    projectId: 'cookiefactory-8018b',
    storageBucket: 'cookiefactory-8018b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ephf5j1UwCuDHVy5lNsd_CbFLhDUPkk',
    appId: '1:849158029445:ios:84188f51253587639de9ec',
    messagingSenderId: '849158029445',
    projectId: 'cookiefactory-8018b',
    storageBucket: 'cookiefactory-8018b.appspot.com',
    iosClientId: '849158029445-b7rbe3oovep66jfcp8jegb8hro5knfn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookieOrdersService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ephf5j1UwCuDHVy5lNsd_CbFLhDUPkk',
    appId: '1:849158029445:ios:84188f51253587639de9ec',
    messagingSenderId: '849158029445',
    projectId: 'cookiefactory-8018b',
    storageBucket: 'cookiefactory-8018b.appspot.com',
    iosClientId: '849158029445-b7rbe3oovep66jfcp8jegb8hro5knfn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookieOrdersService',
  );
}
